// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpqwZJZkELl6EHfc3hn2HoGnx8oX5xyP4',
    appId: '1:28023208610:web:f9b15a4625f6bc309135fb',
    messagingSenderId: '28023208610',
    projectId: 'katies-sunday-klub',
    authDomain: 'katies-sunday-klub.firebaseapp.com',
    storageBucket: 'katies-sunday-klub.firebasestorage.app',
    measurementId: 'G-VLSQD5HRGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNpeLNf-xKc2ruGoU_Y2J5UtDMYko3-GU',
    appId: '1:28023208610:android:23513898a91eebd59135fb',
    messagingSenderId: '28023208610',
    projectId: 'katies-sunday-klub',
    storageBucket: 'katies-sunday-klub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvpqCxjsVzrWYgFvnKzjIEfzf3a1QGIbU',
    appId: '1:28023208610:ios:5138dcc083113f8b9135fb',
    messagingSenderId: '28023208610',
    projectId: 'katies-sunday-klub',
    storageBucket: 'katies-sunday-klub.firebasestorage.app',
    iosBundleId: 'app.katiessundayklub.katiesSundayKlub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvpqCxjsVzrWYgFvnKzjIEfzf3a1QGIbU',
    appId: '1:28023208610:ios:5138dcc083113f8b9135fb',
    messagingSenderId: '28023208610',
    projectId: 'katies-sunday-klub',
    storageBucket: 'katies-sunday-klub.firebasestorage.app',
    iosBundleId: 'app.katiessundayklub.katiesSundayKlub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpqwZJZkELl6EHfc3hn2HoGnx8oX5xyP4',
    appId: '1:28023208610:web:99c501b719310a1b9135fb',
    messagingSenderId: '28023208610',
    projectId: 'katies-sunday-klub',
    authDomain: 'katies-sunday-klub.firebaseapp.com',
    storageBucket: 'katies-sunday-klub.firebasestorage.app',
    measurementId: 'G-DQ03XFS1RS',
  );
}
